//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 the maintenance-orchestrator authors.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalSpec) DeepCopyInto(out *ApprovalSpec) {
	*out = *in
	if in.Gates != nil {
		in, out := &in.Gates, &out.Gates
		*out = make([]GateDecision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ApprovalSpec.
func (in *ApprovalSpec) DeepCopy() *ApprovalSpec {
	if in == nil {
		return nil
	}
	out := new(ApprovalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Batch) DeepCopyInto(out *Batch) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new Batch.
func (in *Batch) DeepCopy() *Batch {
	if in == nil {
		return nil
	}
	out := new(Batch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionPlan) DeepCopyInto(out *ExecutionPlan) {
	*out = *in
	if in.Batches != nil {
		in, out := &in.Batches, &out.Batches
		*out = make([]Batch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RiskFactors != nil {
		in, out := &in.RiskFactors, &out.RiskFactors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Impact = in.Impact
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ExecutionPlan.
func (in *ExecutionPlan) DeepCopy() *ExecutionPlan {
	if in == nil {
		return nil
	}
	out := new(ExecutionPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GateDecision) DeepCopyInto(out *GateDecision) {
	*out = *in
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new GateDecision.
func (in *GateDecision) DeepCopy() *GateDecision {
	if in == nil {
		return nil
	}
	out := new(GateDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImpactEstimate) DeepCopyInto(out *ImpactEstimate) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ImpactEstimate.
func (in *ImpactEstimate) DeepCopy() *ImpactEstimate {
	if in == nil {
		return nil
	}
	out := new(ImpactEstimate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenancePolicy) DeepCopyInto(out *MaintenancePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new MaintenancePolicy.
func (in *MaintenancePolicy) DeepCopy() *MaintenancePolicy {
	if in == nil {
		return nil
	}
	out := new(MaintenancePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintenancePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenancePolicyList) DeepCopyInto(out *MaintenancePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaintenancePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new MaintenancePolicyList.
func (in *MaintenancePolicyList) DeepCopy() *MaintenancePolicyList {
	if in == nil {
		return nil
	}
	out := new(MaintenancePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintenancePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenancePolicySpec) DeepCopyInto(out *MaintenancePolicySpec) {
	*out = *in
	if in.ControlPlaneNodeLabels != nil {
		in, out := &in.ControlPlaneNodeLabels, &out.ControlPlaneNodeLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReservedNodeLabels != nil {
		in, out := &in.ReservedNodeLabels, &out.ReservedNodeLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReservedTaints != nil {
		in, out := &in.ReservedTaints, &out.ReservedTaints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedWindows != nil {
		in, out := &in.AllowedWindows, &out.AllowedWindows
		*out = make([]Window, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new MaintenancePolicySpec.
func (in *MaintenancePolicySpec) DeepCopy() *MaintenancePolicySpec {
	if in == nil {
		return nil
	}
	out := new(MaintenancePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenancePolicyStatus) DeepCopyInto(out *MaintenancePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new MaintenancePolicyStatus.
func (in *MaintenancePolicyStatus) DeepCopy() *MaintenancePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MaintenancePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceRequest) DeepCopyInto(out *MaintenanceRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new MaintenanceRequest.
func (in *MaintenanceRequest) DeepCopy() *MaintenanceRequest {
	if in == nil {
		return nil
	}
	out := new(MaintenanceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintenanceRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceRequestList) DeepCopyInto(out *MaintenanceRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaintenanceRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new MaintenanceRequestList.
func (in *MaintenanceRequestList) DeepCopy() *MaintenanceRequestList {
	if in == nil {
		return nil
	}
	out := new(MaintenanceRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintenanceRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceSpec) DeepCopyInto(out *MaintenanceSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	out.DrainTimeout = in.DrainTimeout
	out.GlobalTimeout = in.GlobalTimeout
	if in.MaintenanceWindow != nil {
		in, out := &in.MaintenanceWindow, &out.MaintenanceWindow
		*out = new(Window)
		(*in).DeepCopyInto(*out)
	}
	in.Approval.DeepCopyInto(&out.Approval)
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(PolicyRef)
		**out = **in
	}
	if in.Upgrade != nil {
		in, out := &in.Upgrade, &out.Upgrade
		*out = new(UpgradeSpec)
		**out = **in
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new MaintenanceSpec.
func (in *MaintenanceSpec) DeepCopy() *MaintenanceSpec {
	if in == nil {
		return nil
	}
	out := new(MaintenanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceStatus) DeepCopyInto(out *MaintenanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Preflight != nil {
		in, out := &in.Preflight, &out.Preflight
		*out = make([]PreflightCheckResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(ExecutionPlan)
		(*in).DeepCopyInto(*out)
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeExecutionStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Summary = in.Summary
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new MaintenanceStatus.
func (in *MaintenanceStatus) DeepCopy() *MaintenanceStatus {
	if in == nil {
		return nil
	}
	out := new(MaintenanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeExecutionStatus) DeepCopyInto(out *NodeExecutionStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new NodeExecutionStatus.
func (in *NodeExecutionStatus) DeepCopy() *NodeExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(NodeExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRef) DeepCopyInto(out *PolicyRef) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new PolicyRef.
func (in *PolicyRef) DeepCopy() *PolicyRef {
	if in == nil {
		return nil
	}
	out := new(PolicyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreflightCheckResult) DeepCopyInto(out *PreflightCheckResult) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new PreflightCheckResult.
func (in *PreflightCheckResult) DeepCopy() *PreflightCheckResult {
	if in == nil {
		return nil
	}
	out := new(PreflightCheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProgressSummary) DeepCopyInto(out *ProgressSummary) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProgressSummary.
func (in *ProgressSummary) DeepCopy() *ProgressSummary {
	if in == nil {
		return nil
	}
	out := new(ProgressSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
	if in.NodeNames != nil {
		in, out := &in.NodeNames, &out.NodeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeSpec) DeepCopyInto(out *UpgradeSpec) {
	*out = *in
	out.ReplacementTimeout = in.ReplacementTimeout
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new UpgradeSpec.
func (in *UpgradeSpec) DeepCopy() *UpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Window) DeepCopyInto(out *Window) {
	*out = *in
	out.Duration = in.Duration
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new Window.
func (in *Window) DeepCopy() *Window {
	if in == nil {
		return nil
	}
	out := new(Window)
	in.DeepCopyInto(out)
	return out
}
